# Generated by Django 3.2.12 on 2022-02-18 02:39

from django.db import migrations, models
import usermanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_alter_bloguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=usermanage.models.custom_path, verbose_name='头像'),
        ),
    ]
