# Generated by Django 3.2.12 on 2022-02-18 01:35

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
